version: '3'
services:
  wichtelnng-db:
    container_name: wichtelnng-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wichteln
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  wichtelnng-app:
    container_name: wichtelnng-app
    image: com.romanboehm/wichtelnng:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wichtelnng-db:5432/wichtelnng
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      LOGGING_LEVEL_COM_ROMANBOEHM_WICHTELNNG: DEBUG
    depends_on:
      - wichtelnng-db